i = int(input("enter a number: "))
f = float(input("enter a number: "))
s = (input("enter a string: "))
l = list(input("enter a list: "))
print(type(i),i)
print(type(f),f)
print(type(s),s)
print(type(l),l)